name: "Chromatic Deployment"

on:
  push:
    branches:
      - front

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # sparse checkout은 특정 디렉토리만 체크아웃하는 옵션
          sparse-checkout: |
            ./Front

      - name: Install dependencies
        run: |
          cd Front
          npm install

      - name: Run Chromatic
        run: |
          cd Front
          npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes --auto-accept-changes
