name: "Chromatic Deployment"

on:
  push:
    branches:
      - front

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # sparse checkout은 특정 디렉토리만 체크아웃하는 옵션
          sparse-checkout: |
            ./Front

      - name: Install dependencies
        run: npm install

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
