name: SonarCloud Scan

on:
  push:
    branches:
      - front
  pull_request:
    branches:
      - front

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install dependencies
        working-directory: Front
        run: npm install

      - name: Run tests (Frontend)
        working-directory: Front
        run: npm run test:ci

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          -Dsonar.token=$SONAR_TOKEN
